# Generated by Django 5.0.7 on 2024-07-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesacb',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
